config/routes.rb
Rails.application.routes.draw do
  resources :publishers, only: %i(create update new show destroy) do
    collection do
      # Registrations, eventually we should consider refactoring these routes into something a little more restful
      scope controller: "registrations", module: "publishers" do
        get :sign_up
        get :log_in
        get :expired_authentication_token
        post :resend_authentication_email

        resource :registrations, only: [:create, :update]
      end

      scope module: "publishers" do
        resource :case do
          delete :delete_file
        end
        resources :case_notes

        scope controller: "uphold" do
          get :uphold_status
          get :uphold_verified, action: :create
          patch :connect_uphold
          patch :disconnect_uphold, action: :destroy
          patch :confirm_default_currency
        end

        resources :statements, only: [:index, :show]
        resource :two_factor_authentications_removal
      end

      get :log_out
      get :home
      get :change_email
      get :change_email_confirm
      patch :update_email
      get :email_verified
      get :wallet
      get :suspended_error
      get :get_site_banner_data
      patch :verify
      patch :update
      patch :complete_signup
      get :choose_new_channel_type
      get :security, to: "publishers/security#index"
      get :prompt_security, to: "publishers/security#prompt"
      get :settings, to: "publishers/settings#index"

      resources :two_factor_authentications, only: %i(index)
      resources :u2f_registrations, only: %i(new create destroy)
      resources :u2f_authentications, only: %i(create)
      resources :totp_registrations, only: %i(new create destroy)
      resources :totp_authentications, only: %i(create)
      resources :promo_registrations, only: %i(index create)
    end
    resources :site_banners, controller: "publishers/site_banners" do
      collection do
        post :set_default_site_banner_mode
      end
    end
    # (Albert Wang): Need to factor the above promo_registrations, as they should be in Publishers::PromoRegistrationsController rather than in the PromoRegistrationsController
    resources :promo_registrations, controller: "publishers/promo_registrations", only: [] do
      collection do
        get :for_referral_code
        get :overview
      end
    end
  end

  namespace :partners do
    resource :payments, only: [:show] do
      resources :invoices do
        resources :invoice_files, only: [:create, :update, :destroy]
      end
    end
    resources :referrals do
      collection do
        resources :promo_registrations
        resources :promo_campaigns
      end
    end
  end

  devise_for :publishers, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "publishers/omniauth_callbacks" }

  resources :channels, only: %i(destroy) do
    member do
      get :verification_status
      get :cancel_add
      delete :destroy
      resources :tokens, only: %() do
        get :reject_transfer, to: "channel_transfer#reject_transfer"
      end
    end
  end

  resources :site_channels, only: %i(create update new show) do
    member do
      patch :update_unverified
      patch :check_for_https
      patch :verify
      get :download_verification_file
      get :verification_choose_method
      get :verification_dns_record
      get :verification_public_file
      get :verification_github
      get :verification_wordpress
    end
  end

  resources :static, only: [] do
    collection do
      get :index
    end
  end

  resources :faqs, only: [:index]

  root "static#index"
  get "no_js", controller: "static"
  get "sign-up", to: "static#index"
  get "log-in", to: "static#index"

  namespace :api, defaults: { format: :json } do
    # /api/v1/
    namespace :v1, defaults: { format: :json } do
      resources :publishers, defaults: { format: :json } do
        post "publisher_status_updates"
      end
      # /api/v1/stats/
      namespace :stats, defaults: { format: :json } do
        namespace :channels, defaults: { format: :json } do
          get :twitch_channels_by_view_count
          get :youtube_channels_by_view_count
        end
        resources :channels, defaults: { format: :json }, only: %i(show)
        resources :promo_campaigns, defaults: { format: :json }, only: %i(index show)
        resources :referral_codes, defaults: { format: :json }, only: %i(index show)
        namespace :publishers, defaults: { format: :json } do
          get :signups_per_day
          get :email_verified_signups_per_day
          get :channel_and_email_verified_signups_per_day
          get :channel_uphold_and_email_verified_signups_per_day
          get :channel_and_kyc_uphold_and_email_verified_signups_per_day
          get :javascript_enabled_usage
          get :totals
        end
      end
      # /api/v1/public/
      namespace :public, defaults: { format: :json } do
        get "channels", controller: "channels"
        namespace :channels, defaults: { format: :json } do
          get "totals"
        end
      end
    end
    # /api/v2/
    namespace :v2, defaults: { format: :json } do
      namespace :public, defaults: { format: :json } do
        get "channels", controller: "channels"
        namespace :channels, defaults: { format: :json } do
          get "totals"
        end
      end
    end
    # /api/v3/
    namespace :v3, defaults: { format: :json } do
      namespace :public, defaults: { format: :json } do
        get "channels", controller: "channels"
        namespace :channels, defaults: { format: :json } do
          get "totals"
        end
      end
    end
  end

  namespace :admin do
    resources :channels, only: [:index] do
      collection do
        get :duplicates
      end
    end

    resources :cases do
      patch :assign
      collection do
        get :overview
        resources :case_replies
      end
    end

    resources :case_notes

    resources :faq_categories, except: [:show]
    resources :faqs, except: [:show]
    resources :payout_reports do
      collection do
        post :notify
        post :upload_settlement_report
        post :toggle_payout_in_progress
      end
      member do
        get :download
        patch :refresh
      end
    end
    resources :publishers do
      collection do
        patch :approve_channel
        get :statement
        get :cancel_two_factor_authentication_removal
      end

      resources :payments
      patch :refresh_uphold

      resources :publisher_notes
      resources :publisher_status_updates, controller: "publishers/publisher_status_updates"
      resources :referrals, controller: "publishers/referrals"
      resources :reports
    end
    resources :channel_transfers
    resources :channel_approvals
    resources :security

    resources :organizations, except: [:destroy]
    resources :partners, except: [:destroy] do
      get :generate_manual_payout
      resources :invoices do
        post :upload
        get :finalize
        patch :update_status
      end
    end

    namespace :stats do
      resources :contributions, only: [:index]
      resources :referrals, only: [:index]
      resources :top_balances, only: [:index]
      resources :top_youtube_channels, only: [:index]
      resources :publisher_statistics, only: [:index]
    end
    resources :unattached_promo_registrations, only: %i(index create) do
      collection do
        get :report, defaults: { format: :csv }
        patch :update_statuses
        patch :assign_campaign
        put :assign_installer_type
      end
    end
    resources :promo_campaigns, only: %i(create)
    root to: "dashboard#index" # <--- Root route

    resources :uphold_status_reports, only: [:index, :show]
  end

  resources :errors, only: [], path: "/" do
    collection do
      get "400", action: :error_400
      get "401", action: :error_401
      get "403", action: :error_403
      get "404", action: :error_404
      get "422", action: :error_422
      get "500", action: :error_500
    end
  end

  require "sidekiq/web"
  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      # Protect against timing attacks: (https://codahale.com/a-lesson-in-timing-attacks/)
      # - Use & (do not use &&) so that it doesn't short circuit.
      # - Use `secure_compare` to stop length information leaking
      ActiveSupport::SecurityUtils.secure_compare(username, ENV["SIDEKIQ_USERNAME"]) &
        ActiveSupport::SecurityUtils.secure_compare(password, ENV["SIDEKIQ_PASSWORD"])
    end
  end
  mount Sidekiq::Web, at: "/magic"
  require "sidekiq/api"
  match "mailer-queue-status" => proc { [200, { "Content-Type" => "text/plain" }, [Sidekiq::Queue.new("mailer").size < 100 ? "OK" : "UHOH"]] }, via: :get
  match "default-queue-status" => proc { [200, { "Content-Type" => "text/plain" }, [Sidekiq::Queue.new("default").size < 5000 ? "OK" : "UHOH"]] }, via: :get
  match "scheduler-queue-status" => proc { [200, { "Content-Type" => "text/plain" }, [Sidekiq::Queue.new("scheduler").size < 5000 ? "OK" : "UHOH"]] }, via: :get
  match "transactional-queue-status" => proc { [200, { "Content-Type" => "text/plain" }, [Sidekiq::Queue.new("transactional").size < 5000 ? "OK" : "UHOH"]] }, via: :get
end

app/controllers/admin/cases_controller.rb
module Admin
  class CasesController < AdminController
    include ActiveRecord::Sanitization::ClassMethods

    before_action :redirect_on_no_filter, only: [:index]

    def index
      @cases = Case.all
      @cases = search if params[:q].present?

      if sort_column == :id
        @cases = @cases.order(open_at: :asc)
      else
        @cases = @cases.order(sanitize_sql_for_order("#{sort_column} #{sort_direction} NULLS LAST"))
      end

      @cases = @cases.paginate(page: params[:page])

      @open_cases = Case.where(status: Case::OPEN)
      @assigned_cases = Case.where(assignee: current_user, status: Case::IN_PROGRESS)
    end

    def search
      search_case = Case
      query = params[:q].strip.downcase
      return search_case if query.blank?

      # Search by case
      if query.include?("#") || query.length == 5
        case_id = query.split('#').second
        case_id = query if case_id.blank?
        search_case = Case.where("case_number = ?", case_id)
      elsif query.include?(":")
        # Search for each type on the db model, like assignee = ""
        query.split(' ').each do |term|
          type, value = term.split(':')
          case type
          when 'assigned'
            @assigned = Publisher.where('email like ? AND role = ?', "%#{value}%", 'admin').first
            search_case = search_case.joins(:assignee).where('publishers.email LIKE ?', "%#{value}%")
          when 'status'
            # Remove all non-alphanumeric values from the status field
            value = value.gsub(/[^0-9a-z_]/i, '')
            search_case = search_case.where('status LIKE ?', "%#{value}%") if value.present?
          end
        end
      else
        search_query = "%#{query}%"
        search_case = Case.joins(:publisher).where('publishers.name LIKE ?', search_query).or(
          Case.joins(:publisher).where('publishers.email LIKE ?', search_query)
        )
      end

      search_case
    end

    def overview
      @open_cases = Case.where(status: Case::OPEN)
      @assigned_cases = Case.where(assignee: current_user, status: Case::IN_PROGRESS)

      @case_status = Case.all.group(:status).count
      @assigned = Case.all.joins(:assignee).group('publishers.name', :status).count

      @assigned = @assigned.sort_by { |x, y| y }.reverse

      @assigned = @assigned.to_a
    end

    def show
      @case = Case.find(params[:id])
      @notes = @case.case_notes.order(created_at: :desc)

      last_note = @notes.where(public: true).first
      @answered = last_note&.created_by&.admin?

      @replies = CaseReply.all
    end

    def assign
      @case = Case.find(params[:case_id])
      assignee = current_user
      assignee = Publisher.where("email LIKE ? AND role='admin'", "#{params[:email].strip}%").first if params[:email].present?

      @case.update(assignee: assignee)
      redirect_to admin_case_path(@case)
    end

    def update
      @case = Case.find(params[:id])

      if @case.update(status: params[:status]) && params[:status] == Case::RESOLVED
        note = PublisherNote.create(
          publisher: @case.publisher,
          created_by: current_user,
          note: "The case was marked as 'Resolved' which triggered this state change to Active."
        )
        @case.publisher.status_updates.create(status: PublisherStatusUpdate::ACTIVE, publisher_note: note)
      end

      redirect_to admin_cases_path
    end

    def has_filter?
      !params[:status].nil? || params[:assigned].present? || params[:q].present? || sort_column != :id
    end

    def sortable_columns
      [:open_at, :assignee_id, :status]
    end

    def redirect_on_no_filter
      return if  has_filter?

      if Case.where(assignee: current_user, status: Case::IN_PROGRESS).size.positive?
        redirect_to admin_cases_path(q: "status:#{Case::IN_PROGRESS} assigned:#{current_user.email.sub("@brave.com", '')}") and return
      else
        redirect_to admin_cases_path(q: "status:#{Case::OPEN}")
      end
    end
  end
end

app/controllers/admin/publishers/publisher_status_updates_controller.rb
class Admin::Publishers::PublisherStatusUpdatesController < Admin::PublishersController
  def index
    get_publisher
    @navigation_view = Views::Admin::NavigationView.new(@publisher).as_json.merge({ navbarSelection: "Dashboard" }).to_json
    @publisher_status_updates = @publisher.status_updates
  end

  def create
    note = @publisher.notes.create(note: params[:note], created_by_id: current_publisher.id)
    @publisher.status_updates.create(status: params[:publisher_status], publisher_note: note)
    @publisher.reload

    # TODO: Send emails for other manual status updates, and send email without creating a status update
    if params[:send_email].present?
      case params[:publisher_status]
      when PublisherStatusUpdate::SUSPENDED
        PublisherMailer.suspend_publisher(@publisher).deliver_later
      when PublisherStatusUpdate::HOLD
        PublisherMailer.email_user_on_hold(@publisher).deliver_later
      end
    end

    if @publisher.only_user_funds?
      flash[:alert] = "FYI: The promo registrations have not been destroyed for this user - however they will not see their promotions"
    end

    flash[:notice] = "Updated publisher's status to #{@publisher.inferred_status}"
    redirect_to admin_publisher_path(id: @publisher.id)
  end
end

app/controllers/admin/publishers/referrals_controller.rb
class Admin::Publishers::ReferralsController < Admin::PublishersController
  def show
    @navigation_view = Views::Admin::NavigationView.new(@publisher).as_json.merge({ navbarSelection: "Referrals" }).to_json
  end
end

app/controllers/api/v1/private/publishers_controller.rb
class Api::V1::Private::PublishersController < Api::V1::Private::BaseController
  class InvalidNote < StandardError; end
  class InvalidAdmin < StandardError; end
  def show
    publisher = Publisher.find(params[:id])
    current_status_update = publisher.last_status_update
    data = {
      id: publisher.id,
      owner_identifier: publisher.owner_identifier,
      email: publisher.email,
      name: publisher.name,
      created_at: publisher.created_at,
      current_status: {
        status: current_status_update.status,
        created_at: current_status_update.created_at,
      },
    }
    render(status: 200, json: data) and return

  rescue ActiveRecord::RecordNotFound
    error_response = {
      errors: [{
        status: "404",
        title: "Not Found",
        detail: "Publisher with id #{params[:publisher_id]} not found",
      },],
    }

    render(status: 404, json: error_response) and return
  end

  def publisher_status_updates
    publisher = Publisher.find(params[:publisher_id])
    admin = Publisher.find_by_email(params[:admin])
    status = params[:status]
    note = params[:note]

    raise InvalidNote if note.blank?
    raise InvalidAdmin if admin.blank?

    PublisherStatusUpdate.create!(publisher: publisher, status: status)
    PublisherNote.create!(note: note, publisher: publisher, created_by: admin)

    render(status: 200, json: { success: "true" }) and return

  rescue ActiveRecord::RecordInvalid
    error_response = {
      error: "Status Invalid",
      detail: "Status #{params[:status]} is not valid, please use one of the following: #{PublisherStatusUpdate::ALL_STATUSES.join(", ")}",
    }

    render(status: 404, json: error_response) and return

  rescue InvalidNote
    error_response = {
      error: "Note Invalid",
      detail: "Note cannot be null, please provide justification for status update",
    }

    render(status: 404, json: error_response) and return

  rescue InvalidAdmin
    error_response = {
      error: "Admin Invalid",
      detail: "Admin field cannot be null, please provide e-mail of an admin",
    }

    render(status: 404, json: error_response) and return

  rescue ActiveRecord::RecordNotFound
    error_response = {
      error: "Not Found",
      detail: "Publisher with id #{params[:publisher_id]} not found",
    }

    render(status: 404, json: error_response) and return
  end
end

app/controllers/publishers/security_controller.rb
require "concerns/two_factor_registration"

module Publishers
  class SecurityController < ApplicationController
    include PublishersHelper
    include TwoFactorRegistration

    before_action :authenticate_publisher!

    def index
      @u2f_registrations = current_publisher.u2f_registrations
    end

    def prompt
      flag_2fa_registration_during_signup
    end
  end
end

app/views/publishers/cases/_file.html.slim
.c-4.m-3.shadow-sm.rounded.p-3
  - if file.blob.image?
    = image_tag file, class: "screenshot img-thumbnail img-fluid"
  .ml-2.mt-3=file.blob.filename

app/views/publishers/cases/_message.html.slim
.note.mt-3.rounded.p-2 class="#{message.public? ? '' : 'private-message' }"

  .d-flex
    .avatar.mr-2
      - if message.created_by.admin? && message.public?
        .border.rounded-circle.text-center.bg-white style="width:42px; height: 42px;"
          .my-1=render "logo_svg"
      - else
        .u-avatar style="background: ##{message.created_by.avatar_color};"= render "avatar_svg"
    .content.w-100
      .note-header
        / The name of the person
        - if message.created_by.admin?
          - if message.public?
            = t(".support")
          - else
            = message.created_by.name
        - else
          strong= message.created_by.name
        / Bullet point
        small.text-muted.mx-2 &#149;

        / Time it was created
        span.date data-tooltip=message.created_at.strftime("%B %d, %Y %k:%M %Z")
          = time_ago_in_words(message.created_at)
          span= t(".ago")

        - if current_publisher.admin? && message.public? && message.created_by.admin?
          small.text-muted.mx-2 &#149;
          = link_to fa_icon("eye-slash", text: 'Make internal'), admin_case_note_path(message), method: :patch, class: 'text-dark font-weight-bold'

      / Actual content of the note
      div id="content_#{message.id}" class="my-3"
        = simple_format(message.note, sanitize: true)

        - if message.files.size > 0
          .mt-5.font-weight-bold= t(".attachments")
          .row
            - message.files.each do |file|
              = render partial: 'publishers/cases/file', locals: { file: file}




    - unless message.public?
      div.ml-3
        =fa_icon "eye-slash 5x", class: 'text-white'

app/views/publishers/cases/new.html.slim
- content_for(:navbar_content_right) do
  = link_to( \
    t("shared.dashboard"), \
    home_publishers_path, \
    class: 'title' \
  )
  - if current_publisher.partner?
    = link_to(t("shared.referrals"), partners_referrals_path, class: 'title-partner')
    = link_to(t("shared.payments"), partners_payments_path, class: 'title-partner' )

  = render partial: "choose_channel_button"

.container.container-panel
  .p-4
    h2= t('.title')
    / span.warning-icon.mr-2
    /   = render 'icon_circled_bang_warning'
    .pr-5
      == t('publishers.cases.shared.description')

    = form_with model: @case, local: false, id: "case-form", class: "mt-4" do |f|
      .form-group
        label
         strong== t('publishers.cases.shared.solicit_question')
        = f.text_area :solicit_question, { class:'form-control', rows:'7',  minlength: "50", placeholder: t('publishers.cases.shared.placeholder') }
      .form-group
        label
         strong== t('publishers.cases.shared.accident_question')
        = f.text_area :accident_question, { class:'form-control', rows:'7',  minlength: "50", placeholder: t('publishers.cases.shared.alert') }

      .form-group
        label
          strong= t('publishers.cases.shared.evidence')

        #fileUploadSection
        = f.file_field :files, multiple: true, class: 'd-none'
        .row
          - @case.files.each do |file|
            .c-4.m-3.shadow-sm.rounded.p-3
              =link_to file.blob.filename, url_for(file)
              = link_to "(x)", delete_file_case_path(id: file.id), method: :delete, class: 'ml-2 text-danger'


      .d-flex.align-items-center
        a.btn.btn-primary#open-case href="#" =t('.submit')
        = link_to t('.cancel'), home_publishers_path, class: 'ml-4 btn btn-secondary'

        .autosave.ml-3.d-flex
          h5.d-none#saving
            .badge.badge-light =t('publishers.cases.shared.saving')
          h5.fade#saved
            .badge.badge-success =t('publishers.cases.shared.saved')

=javascript_pack_tag 'case'

app/views/publishers/cases/show.html.slim
- content_for(:navbar_content_right) do
  = link_to( \
    t("shared.dashboard"), \
    home_publishers_path, \
    class: 'title' \
  )
  - if current_publisher.partner?
    = link_to(t("shared.referrals"), partners_referrals_path, class: 'title-partner')
    = link_to(t("shared.payments"), partners_payments_path, class: 'title-partner' )

  = render partial: "choose_channel_button"

.container.container-panel.mb-4
  = render "panel_flash_messages"
  .p-3
    .d-flex.justify-content-between.align-items-center
      h2
        = t('.title')
        small.ml-4= case_badge(@case.status)
      small= t(".last_updated_at", time: time_ago_in_words(@case.updated_at))
    hr

    - unless @case.closed? || @case.resolved?
      .my-3.alert.alert-primary= t(".notice")
    .form-group
      label
        strong= t('publishers.cases.shared.solicit_question')
      p=simple_format(@case.solicit_question, sanitize: true)

    .form-group
      label
        strong= t('publishers.cases.shared.accident_question')
      p=simple_format(@case.accident_question, sanitize: true)

    .form-group
      label
        strong= t('publishers.cases.shared.evidence')
      .row
        - @case.files.each do |file|
          = render partial: 'file', locals: { file: file}


- if @notes.present?
  .container.container-panel.mb-4
    .p-3
      h3 = t('.messages')
      - @notes.each do |message|
        = render partial: 'message', locals: { message: message }


- if @case.open? || @case.in_progress?
  .container.container-panel
    .p-3
      h3 = t('.new_message_title')
      p =t(".note_description")

      = form_with model: CaseNote.new, local: true, id: "case-form" do |f|
        .form-group
          = f.text_area :note, { class:'form-control', rows:'6', minlength: "5", }
        .form-group
          = f.file_field :files, multiple: true

        =submit_tag(t('.send_message'), class: "btn btn-primary")

app/views/publishers/cases/update.js.erb
if(<%= @case.errors.full_messages.length.positive? %>) {

  const errorMessage = document.createElement("div");
  errorMessage.classList = "mt-3 alert alert-warning";
  errorMessage.innerHTML = "<%=@case.errors.full_messages.join(", ") %>";
  const form = document.querySelector("form");
  form.appendChild(errorMessage);
}
console.log("<%= @case.errors.full_messages %>")

const inputFile = document.getElementsByName("case[files][]")[0]
inputFile.value = null;

document.getElementById("saved").classList.toggle("visible");
document.getElementById("saving").classList.toggle("d-none");

// second later hide this
setTimeout(function() {
  document.getElementById("saved").classList.toggle("visible");
}, 1000);