config/routes.rb
Rails.application.routes.draw do
  resources :publishers, only: %i(create update new show destroy) do
    collection do
      # Registrations, eventually we should consider refactoring these routes into something a little more restful
      scope controller: "registrations", module: "publishers" do
        get :sign_up
        get :log_in
        get :expired_authentication_token
        post :resend_authentication_email

        resource :registrations, only: [:create, :update]
      end

      scope module: "publishers" do
        resource :case do
          delete :delete_file
        end
        resources :case_notes

        scope controller: "uphold" do
          get :uphold_status
          get :uphold_verified, action: :create
          patch :connect_uphold
          patch :disconnect_uphold, action: :destroy
          patch :confirm_default_currency
        end

        resources :statements, only: [:index, :show]
        resource :two_factor_authentications_removal
      end

      get :log_out
      get :home
      get :change_email
      get :change_email_confirm
      patch :update_email
      get :email_verified
      get :wallet
      get :suspended_error
      get :get_site_banner_data
      patch :verify
      patch :update
      patch :complete_signup
      get :choose_new_channel_type
      get :security, to: "publishers/security#index"
      get :prompt_security, to: "publishers/security#prompt"
      get :settings, to: "publishers/settings#index"

      resources :two_factor_authentications, only: %i(index)
      resources :u2f_registrations, only: %i(new create destroy)
      resources :u2f_authentications, only: %i(create)
      resources :totp_registrations, only: %i(new create destroy)
      resources :totp_authentications, only: %i(create)
      resources :promo_registrations, only: %i(index create)
    end
    resources :site_banners, controller: "publishers/site_banners" do
      collection do
        post :set_default_site_banner_mode
      end
    end
    # (Albert Wang): Need to factor the above promo_registrations, as they should be in Publishers::PromoRegistrationsController rather than in the PromoRegistrationsController
    resources :promo_registrations, controller: "publishers/promo_registrations", only: [] do
      collection do
        get :for_referral_code
        get :overview
      end
    end
  end

  namespace :partners do
    resource :payments, only: [:show] do
      resources :invoices do
        resources :invoice_files, only: [:create, :update, :destroy]
      end
    end
    resources :referrals do
      collection do
        resources :promo_registrations
        resources :promo_campaigns
      end
    end
  end

  devise_for :publishers, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "publishers/omniauth_callbacks" }

  resources :channels, only: %i(destroy) do
    member do
      get :verification_status
      get :cancel_add
      delete :destroy
      resources :tokens, only: %() do
        get :reject_transfer, to: "channel_transfer#reject_transfer"
      end
    end
  end

  resources :site_channels, only: %i(create update new show) do
    member do
      patch :update_unverified
      patch :check_for_https
      patch :verify
      get :download_verification_file
      get :verification_choose_method
      get :verification_dns_record
      get :verification_public_file
      get :verification_github
      get :verification_wordpress
    end
  end

  resources :static, only: [] do
    collection do
      get :index
    end
  end

  resources :faqs, only: [:index]

  root "static#index"
  get "no_js", controller: "static"
  get "sign-up", to: "static#index"
  get "log-in", to: "static#index"

  namespace :api, defaults: { format: :json } do
    # /api/v1/
    namespace :v1, defaults: { format: :json } do
      resources :publishers, defaults: { format: :json } do
        post "publisher_status_updates"
      end
      # /api/v1/stats/
      namespace :stats, defaults: { format: :json } do
        namespace :channels, defaults: { format: :json } do
          get :twitch_channels_by_view_count
          get :youtube_channels_by_view_count
        end
        resources :channels, defaults: { format: :json }, only: %i(show)
        resources :promo_campaigns, defaults: { format: :json }, only: %i(index show)
        resources :referral_codes, defaults: { format: :json }, only: %i(index show)
        namespace :publishers, defaults: { format: :json } do
          get :signups_per_day
          get :email_verified_signups_per_day
          get :channel_and_email_verified_signups_per_day
          get :channel_uphold_and_email_verified_signups_per_day
          get :channel_and_kyc_uphold_and_email_verified_signups_per_day
          get :javascript_enabled_usage
          get :totals
        end
      end
      # /api/v1/public/
      namespace :public, defaults: { format: :json } do
        get "channels", controller: "channels"
        namespace :channels, defaults: { format: :json } do
          get "totals"
        end
      end
    end
    # /api/v2/
    namespace :v2, defaults: { format: :json } do
      namespace :public, defaults: { format: :json } do
        get "channels", controller: "channels"
        namespace :channels, defaults: { format: :json } do
          get "totals"
        end
      end
    end
    # /api/v3/
    namespace :v3, defaults: { format: :json } do
      namespace :public, defaults: { format: :json } do
        get "channels", controller: "channels"
        namespace :channels, defaults: { format: :json } do
          get "totals"
        end
      end
    end
  end

  namespace :admin do
    resources :channels, only: [:index] do
      collection do
        get :duplicates
      end
    end

    resources :cases do
      patch :assign
      collection do
        get :overview
        resources :case_replies
      end
    end

    resources :case_notes

    resources :faq_categories, except: [:show]
    resources :faqs, except: [:show]
    resources :payout_reports do
      collection do
        post :notify
        post :upload_settlement_report
        post :toggle_payout_in_progress
      end
      member do
        get :download
        patch :refresh
      end
    end
    resources :publishers do
      collection do
        patch :approve_channel
        get :statement
        get :cancel_two_factor_authentication_removal
      end

      resources :payments
      patch :refresh_uphold

      resources :publisher_notes
      resources :publisher_status_updates, controller: "publishers/publisher_status_updates"
      resources :referrals, controller: "publishers/referrals"
      resources :reports
    end
    resources :channel_transfers
    resources :channel_approvals
    resources :security

    resources :organizations, except: [:destroy]
    resources :partners, except: [:destroy] do
      get :generate_manual_payout
      resources :invoices do
        post :upload
        get :finalize
        patch :update_status
      end
    end

    namespace :stats do
      resources :contributions, only: [:index]
      resources :referrals, only: [:index]
      resources :top_balances, only: [:index]
      resources :top_youtube_channels, only: [:index]
      resources :publisher_statistics, only: [:index]
    end
    resources :unattached_promo_registrations, only: %i(index create) do
      collection do
        get :report, defaults: { format: :csv }
        patch :update_statuses
        patch :assign_campaign
        put :assign_installer_type
      end
    end
    resources :promo_campaigns, only: %i(create)
    root to: "dashboard#index" # <--- Root route

    resources :uphold_status_reports, only: [:index, :show]
  end

  resources :errors, only: [], path: "/" do
    collection do
      get "400", action: :error_400
      get "401", action: :error_401
      get "403", action: :error_403
      get "404", action: :error_404
      get "422", action: :error_422
      get "500", action: :error_500
    end
  end

  require "sidekiq/web"
  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      # Protect against timing attacks: (https://codahale.com/a-lesson-in-timing-attacks/)
      # - Use & (do not use &&) so that it doesn't short circuit.
      # - Use `secure_compare` to stop length information leaking
      ActiveSupport::SecurityUtils.secure_compare(username, ENV["SIDEKIQ_USERNAME"]) &
        ActiveSupport::SecurityUtils.secure_compare(password, ENV["SIDEKIQ_PASSWORD"])
    end
  end
  mount Sidekiq::Web, at: "/magic"
  require "sidekiq/api"
  match "mailer-queue-status" => proc { [200, { "Content-Type" => "text/plain" }, [Sidekiq::Queue.new("mailer").size < 100 ? "OK" : "UHOH"]] }, via: :get
  match "default-queue-status" => proc { [200, { "Content-Type" => "text/plain" }, [Sidekiq::Queue.new("default").size < 5000 ? "OK" : "UHOH"]] }, via: :get
  match "scheduler-queue-status" => proc { [200, { "Content-Type" => "text/plain" }, [Sidekiq::Queue.new("scheduler").size < 5000 ? "OK" : "UHOH"]] }, via: :get
  match "transactional-queue-status" => proc { [200, { "Content-Type" => "text/plain" }, [Sidekiq::Queue.new("transactional").size < 5000 ? "OK" : "UHOH"]] }, via: :get
end

app/models/promo_registration.rb
class PromoRegistration < ApplicationRecord
  # A promo registration can belong to a channel,
  # a publisher, or be unattached.  Unattached codes
  # are created by admins.
  CHANNEL = "channel".freeze
  OWNER = "owner".freeze
  UNATTACHED = "unattached".freeze
  KINDS = [CHANNEL, OWNER, UNATTACHED].freeze

  # Event types
  RETRIEVALS = "retrievals".freeze # Aliased as 'Downloads'
  FIRST_RUNS = "first_runs".freeze # Aliased as 'Installs'
  FINALIZED = "finalized".freeze # Aliased as 'Confirmed'

  COUNTRY = "country".freeze

  # Reporting intervals
  DAILY = "daily".freeze
  WEEKLY = "weekly".freeze
  MONTHLY = "monthly".freeze
  RUNNING_TOTAL = "running_total".freeze

  # Installer types
  SILENT = "silent".freeze
  MOBILE = "mobile".freeze
  STANDARD = "standard".freeze

  BASE_STATS = { RETRIEVALS => 0, FIRST_RUNS => 0, FINALIZED => 0 }.freeze

  belongs_to :channel, validate: true, autosave: true
  belongs_to :promo_campaign
  belongs_to :publisher

  validates :channel_id, presence: true, if: -> { kind == CHANNEL }
  validates :publisher_id, presence: true, unless: -> { kind == UNATTACHED }

  validates :promo_id, presence: true
  validates :kind, presence: true
  validates :kind, inclusion: { in: KINDS, message: "%{value} is not a valid kind of promo registration." }
  validates :referral_code, presence: true, uniqueness: { scope: :promo_id }

  scope :owner_only, -> { where(kind: OWNER) }
  scope :unattached_only, -> { where(kind: UNATTACHED) }
  scope :channels_only, -> { where(kind: CHANNEL) }
  scope :has_stats, -> { where.not(stats: "[]") }

  before_destroy :delete_from_promo_server

  def delete_from_promo_server
    Promo::ChannelOwnerUpdater.new(referral_code: referral_code).perform
  end

  # Parses the events associated with a promo registration and returns
  # the aggregate totals for each event type
  def aggregate_stats
    aggregate_stats_by_period(Date.new, Date.tomorrow)
  end

  def aggregate_stats_by_period(period_start, period_end)
    parsed = JSON.parse(stats).select do |event|
      date = event['ymd'].to_date
      date > period_start && date < period_end
    end

    parsed.reduce(BASE_STATS.deep_dup, &PromoRegistration.sum_stats)
  end

  # the stats are currently organized by platform.
  def stats_by_date
    compressed_stats = {}
    starting_date = nil
    JSON.parse(stats).each do |stat|
      starting_date ||= stat['ymd'] if starting_date.nil?
      unless compressed_stats.key?(stat['ymd'])
        compressed_stats[stat['ymd']] = {}
        compressed_stats[stat['ymd']]['retrievals'] = 0
        compressed_stats[stat['ymd']]['first_runs'] = 0
        compressed_stats[stat['ymd']]['finalized'] = 0
        compressed_stats[stat['ymd']]['ymd'] = stat['ymd']
      end
      compressed_stats[stat['ymd']]['retrievals'] += stat['retrievals']
      compressed_stats[stat['ymd']]['first_runs'] += stat['first_runs']
      compressed_stats[stat['ymd']]['finalized'] += stat['finalized']
    end

    return [] if starting_date.nil?

    rolling_date = Date.parse(starting_date)
    while rolling_date < Date.today
      formatted_date = rolling_date.strftime("%Y-%m-%d")
      unless compressed_stats.key?(formatted_date)
        compressed_stats[formatted_date] = {}
        compressed_stats[formatted_date]['retrievals'] = 0
        compressed_stats[formatted_date]['first_runs'] = 0
        compressed_stats[formatted_date]['finalized'] = 0
        compressed_stats[formatted_date]['ymd'] = formatted_date
      end
      rolling_date = rolling_date.tomorrow
    end

    compressed_stats.values.sort_by! { |h| h['ymd'] }
  end

  class << self
    # Returns the aggregate totals for each event type given a
    # ActiveRecord::Association of PromoRegistrations
    def stats_for_registrations(promo_registrations:, start_date: Date.new, end_date: Date.today.at_end_of_day)
      promo_registrations.
        map { |pr| pr.aggregate_stats_by_period(start_date, end_date) }.
        reduce(PromoRegistration::BASE_STATS.deep_dup, &PromoRegistration.sum_stats)
    end

    def sum_stats
      Proc.new do |aggregate_stats, event|
        aggregate_stats[RETRIEVALS] += event[RETRIEVALS]
        aggregate_stats[FIRST_RUNS] += event[FIRST_RUNS]
        aggregate_stats[FINALIZED] += event[FINALIZED]

        aggregate_stats
      end
    end
  end
end

app/controllers/admin/promo_registrations_controller.rb
class Admin::PromoRegistrationsController < AdminController
    def for_referral_code
      publisher = Publisher.find(params[:publisher_id])
      promo_registration = publisher.promo_registrations.find_by(referral_code: params[:referral_code])
      render :unauthorized and return if promo_registration.nil?
      render json: promo_registration.stats_by_date.to_json
    end
end

app/controllers/partners/promo_registrations_controller.rb
module Partners
  class PromoRegistrationsController < ApplicationController
    include PromosHelper
    include ActionView::Helpers::SanitizeHelper
    def create
      Promo::OwnerRegistrar.new(
        number: sanitize(params[:number]).to_i,
        publisher_id: current_publisher.id,
        description: sanitize(params[:description]),
        promo_campaign_id: sanitize(params[:promo_campaign_id])
      ).perform
    end

    def update
      data = sanitize(params[:id]).split(/,/)
      data.each do |code|
        promo_registration = current_publisher.promo_registrations.find(code)
        promo_registration.update(promo_campaign_id: sanitize(params[:campaign]))
      end
    end

    def destroy
      promo_registration = current_publisher.promo_registrations.find(sanitize(params[:id]))
      promo_registration.destroy
    end
  end
end

app/controllers/promo_registrations_controller.rb
class PromoRegistrationsController < ApplicationController
  include PromosHelper
  before_action :authenticate_publisher!
  before_action :require_publisher_promo_disabled, only: %(create)
  before_action :require_promo_running, only: %i(create)

  def index
    @publisher = current_publisher
    @publisher_promo_status = @publisher.promo_status(promo_running?)
    @promo_enabled_channels = @publisher.channels.joins(:promo_registration)
  end

  def create
    @publisher = current_publisher
    @publisher.promo_enabled_2018q1 = true
    @publisher.save!
    current_publisher.channels.left_joins(:promo_registration).where(promo_registrations: {id: nil}).find_each do |channel|
      channel.register_channel_for_promo # Callee does a check
    end
    @promo_enabled_channels = @publisher.channels.joins(:promo_registration)
    @publisher_has_verified_channel = @publisher.has_verified_channel?
  end

  private

  def require_promo_running
    unless promo_running?
      redirect_to promo_registrations_path, action: "index"
    end
  end

  def require_publisher_promo_disabled
    if current_publisher.promo_enabled_2018q1
      redirect_to promo_registrations_path, action: "index"
    end
  end
end

app/controllers/publishers/promo_registrations_controller.rb
class Publishers::PromoRegistrationsController < PublishersController
  def for_referral_code
    promo_registration =
      if current_publisher.admin?
        PromoRegistration.find_by(referral_code: params[:referral_code])
      else
        current_publisher.promo_registrations.find_by(referral_code: params[:referral_code])
      end
    render :unauthorized and return if promo_registration.nil?
    render json: {
      stats: promo_registration.aggregate_stats,
      data: promo_registration.stats_by_date,
    }
  end

  def overview
    start_date = (params[:month]&.to_date || Date.today).at_beginning_of_month
    end_date = start_date.at_end_of_month

    aggregate_stats = PromoRegistration.stats_for_registrations(
      promo_registrations: current_publisher.promo_registrations,
      start_date: start_date,
      end_date: end_date
    )

    groups = Eyeshade::Referrals.new.groups
    statement = Eyeshade::Referrals.new.statement(publisher: current_publisher, start_date: start_date, end_date: end_date)

    groups.each do |group|
      group[:count] = statement.select { |s| s[:groupId] == group[:id] }.length
    end

    # TODO Remove this after November 1st, 2019
    legacy_count = aggregate_stats[PromoRegistration::FINALIZED] - statement.length
    groups << {
      id: SecureRandom.uuid,
      name: 'Previous Rate',
      amount: "5.00",
      currency: "USD",
      count: legacy_count.negative? ? 0 : legacy_count,
    }

    render json: {
      groups: groups,
      totals: aggregate_stats,
    }
  end
end

app/views/promo_registrations/_activate.html.slim
.single-panel--wrapper.single-panel--wrapper--small.promo--panel.promo--panel-activate.text-center
  h4.promo--subtitle = t("promo.activate.sub_header_one")
  .promo--title data-test="promo-activate"= t("promo.activate.header")
  h4.promo--subtitle-alternative = t("promo.activate.sub_header_two")
  .promo--activate-body-container
    p.promo--body-text-alternative= t("promo.activate.description")
    = form_for @publisher, {method: :post, url: promo_registrations_path} do |f|
      = f.hidden_field(:promo_token, :value => params[:promo_token])
      .text-center
        = f.submit(t("promo.activate.button").upcase, class: "btn promo--activate-button", :"data-piwik-action" => "ActivatePromoClicked", :"data-piwik-name" => "Clicked", :"data-piwik-value" => "PromoFlow")

app/views/promo_registrations/_activated_unverified.html.slim
.single-panel--wrapper.single-panel--wrapper--small.promo--panel
  .promo--bat-patch-adjacent
    h1.promo--title data-test="promo-activated-unverified"= t("promo.activated.title")
    h3.promo--subtitle = t("promo.activated.subtitle")
    .promo--item-container.promo--item-container-reward
      span.promo--item-label = t("promo.shared.reward").upcase
      span = t("promo.shared.reward_description")
    p.promo--body-text
      span = t("promo.activated.description_one")
      - if current_publisher
        span = link_to(t("promo.activated.description_two"), home_publishers_path)
      - else
        span = link_to(t("promo.activated.description_two"), log_in_publishers_path)
  .promo--item-container
    span.promo--item-label= t("promo.shared.referral_links")
  p#promo--no-channels = t("promo.activated.unverified_no_channels")
  .promo--unverified-container.text-center
    p.promo--body-text = t("promo.activated.unverified_error")
    - if current_publisher
      = link_to(t("promo.activated.unverified_cta").upcase, home_publishers_path, class: "btn btn-primary promo--activate-button")
    - else
      = link_to(t("promo.activated.unverified_cta").upcase, log_in_publishers_path, class: "btn btn-primary promo--activate-button")

app/views/promo_registrations/_activated_verified.html.slim
.single-panel--wrapper.single-panel--wrapper--small.promo--panel
  .promo--bat-patch-adjacent
    h1.promo--title data-test="promo-activated-verified"= t("promo.activated.title")
    h3.promo--subtitle = t("promo.activated.subtitle")
    .promo--item-container.promo--item-container-reward
      span.promo--item-label = t("promo.shared.reward").upcase
      span = t("promo.shared.reward_description")
    p.promo--body-text.promo--body-text-verified
      span = t("promo.activated.description_one")
      - if current_publisher
        span = link_to(t("promo.activated.description_two"), home_publishers_path)
      - else
        span = link_to(t("promo.activated.description_two"), log_in_publishers_path)
  .promo--item-container
    span.promo--item-label= t("promo.shared.referral_links")
  - n = 0
  - @promo_enabled_channels.each do |channel|
    .promo--referral-link-container-container class="promo--referral-link-container-container-#{n%2}"
      .promo--item-label.promo--item-label-link-name = on_channel_type(channel)
      .promo--referral-link-container
        span.promo--referral-link id="#{channel.promo_registration.referral_code.downcase}" = https_referral_url(channel.promo_registration.referral_code)
        button.copy-button.promo--copy-button data-clipboard-target="##{channel.promo_registration.referral_code.downcase}" = t("promo.shared.copy")
        = link_to("".upcase, tweet_url(channel.promo_registration.referral_code), target: :_blank, class: 'promo--share-button promo--share-button-twitter promo--share-button-desktop')
        = link_to("".upcase, facebook_url(channel.promo_registration.referral_code), target: :_blank, class: 'promo--share-button promo--share-button-facebook promo--share-button-desktop')
      = link_to(t("promo.shared.tweet").upcase, tweet_url(channel.promo_registration.referral_code), target: :_blank, class: 'promo--share-button promo--share-button-mobile promo--share-button-twitter')
      = link_to(t("promo.shared.share").upcase, facebook_url(channel.promo_registration.referral_code), target: :_blank, class: 'promo--share-button promo--share-button-mobile promo--share-button-facebook')
    - n += 1
  p.promo--body-text-mobile
    span = t("promo.activated.description_one")
    - if current_publisher
      span = link_to(t("promo.activated.description_two"), home_publishers_path)
    - else
      span = link_to(t("promo.activated.description_two"), log_in_publishers_path)

app/views/promo_registrations/_active.html.slim
.single-panel--wrapper.single-panel--wrapper--small.promo--panel
  .promo--bat-patch-adjacent
    h1.promo--title.promo--title-active data-test="promo-active"= t("promo.active.title")
    .promo--item-container.promo--item-container-reward
      span.promo--item-label = t("promo.shared.reward").upcase
      span = t("promo.shared.reward_description")
    p.promo--body-text
      span = t("promo.active.description_one")
      span = t("promo.active.description_two")
      - if current_publisher
        span = link_to(t("promo.active.description_three"), home_publishers_path)
      - else
        span = link_to(t("promo.active.description_three"), log_in_publishers_path)
  .promo--item-container
    span.promo--item-label= t("promo.shared.referral_links")
  - n = 0
  - @promo_enabled_channels.each do |channel|
    .promo--referral-link-container-container class="promo--referral-link-container-container-#{n%2}"
      .promo--item-label.promo--item-label-link-name = on_channel_type(channel)
      .promo--referral-link-container
        span.promo--referral-link id="#{channel.promo_registration.referral_code.downcase}" = https_referral_url(channel.promo_registration.referral_code)
        button.copy-button.promo--copy-button data-clipboard-target="##{channel.promo_registration.referral_code.downcase}" = t("promo.shared.copy")
        = link_to("".upcase, tweet_url(channel.promo_registration.referral_code), target: :_blank, class: 'promo--share-button promo--share-button-twitter promo--share-button-desktop')
        = link_to("".upcase, facebook_url(channel.promo_registration.referral_code), target: :_blank, class: 'promo--share-button promo--share-button-facebook promo--share-button-desktop')
      = link_to(t("promo.shared.tweet").upcase, tweet_url(https_referral_url(channel.promo_registration.referral_code)), class: 'promo--share-button promo--share-button-mobile promo--share-button-twitter')
      = link_to(t("promo.shared.share").upcase, facebook_url(https_referral_url(channel.promo_registration.referral_code)), class: 'promo--share-button promo--share-button-mobile promo--share-button-facebook')
    - n += 1
  p.promo--body-text-mobile
    span = t("promo.active.description_one")
    span = t("promo.active.description_two")
    - if current_publisher
      span = link_to(t("promo.active.description_three"), home_publishers_path)
    - else
      span = link_to(t("promo.active.description_three"), log_in_publishers_path)

app/views/promo_registrations/_over.html.slim
.single-panel--wrapper.single-panel--wrapper--small.promo--panel.promo--panel-over
  .promo--bat-patch-adjacent
    h1.promo--title data-test="promo-over"= t("promo.over.title")
    h3.promo--subtitle = t("promo.over.promo_ended")
    p.promo--body-text.promo--body-text-mobile= t("promo.over.description")
    span = link_to(t("promo.over.brave_download_link"), "https://brave.com/download", id: "promo--over-download-link")
  p.promo--body-text.promo--body-text-mobile = t("promo.over.footer")

app/views/promo_registrations/_promo_footer.html.slim
.single-panel--wrapper--small
  .footer--promo.footer--promo-message
    = t("promo.shared.tos_1")
  .footer--promo.footer--promo-message-tos2
    = t("promo.shared.tos_2_html")
  .footer--promo
    .footer--promo-item.footer--promo-item-dashboard
      - if current_publisher
        = link_to(t("promo.shared.brave_rewards_tm"), home_publishers_path)
      - else
        = link_to(t("promo.shared.brave_rewards_tm"), log_in_publishers_path)
    .footer--promo-item.footer--promo-item-tos
      = link_to(t("shared.terms_of_service"), terms_of_service_url)

app/views/promo_registrations/create.html.slim
- if @publisher_has_verified_channel
  = render "activated_verified", locals: @publisher
- else
  = render "activated_unverified", locals: @publisher

app/views/promo_registrations/index.html.slim
- if @publisher_promo_status == :active
  = render "active", locals: @publisher
- elsif @publisher_promo_status == :inactive
  = render "activate", publisher: @publisher, promo_enabled_channels: @promo_enabled_channels
- else
  = render "over", locals: @publisher