config/routes.rb
Rails.application.routes.draw do
  resources :publishers, only: %i(create update new show destroy) do
    collection do
      # Registrations, eventually we should consider refactoring these routes into something a little more restful
      scope controller: "registrations", module: "publishers" do
        get :sign_up
        get :log_in
        get :expired_authentication_token
        post :resend_authentication_email

        resource :registrations, only: [:create, :update]
      end

      scope module: "publishers" do
        resource :case do
          delete :delete_file
        end
        resources :case_notes

        scope controller: "uphold" do
          get :uphold_status
          get :uphold_verified, action: :create
          patch :connect_uphold
          patch :disconnect_uphold, action: :destroy
          patch :confirm_default_currency
        end

        resources :statements, only: [:index, :show]
        resource :two_factor_authentications_removal
      end

      get :log_out
      get :home
      get :change_email
      get :change_email_confirm
      patch :update_email
      get :email_verified
      get :wallet
      get :suspended_error
      get :get_site_banner_data
      patch :verify
      patch :update
      patch :complete_signup
      get :choose_new_channel_type
      get :security, to: "publishers/security#index"
      get :prompt_security, to: "publishers/security#prompt"
      get :settings, to: "publishers/settings#index"

      resources :two_factor_authentications, only: %i(index)
      resources :u2f_registrations, only: %i(new create destroy)
      resources :u2f_authentications, only: %i(create)
      resources :totp_registrations, only: %i(new create destroy)
      resources :totp_authentications, only: %i(create)
      resources :promo_registrations, only: %i(index create)
    end
    resources :site_banners, controller: "publishers/site_banners" do
      collection do
        post :set_default_site_banner_mode
      end
    end
    # (Albert Wang): Need to factor the above promo_registrations, as they should be in Publishers::PromoRegistrationsController rather than in the PromoRegistrationsController
    resources :promo_registrations, controller: "publishers/promo_registrations", only: [] do
      collection do
        get :for_referral_code
        get :overview
      end
    end
  end

  namespace :partners do
    resource :payments, only: [:show] do
      resources :invoices do
        resources :invoice_files, only: [:create, :update, :destroy]
      end
    end
    resources :referrals do
      collection do
        resources :promo_registrations
        resources :promo_campaigns
      end
    end
  end

  devise_for :publishers, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "publishers/omniauth_callbacks" }

  resources :channels, only: %i(destroy) do
    member do
      get :verification_status
      get :cancel_add
      delete :destroy
      resources :tokens, only: %() do
        get :reject_transfer, to: "channel_transfer#reject_transfer"
      end
    end
  end

  resources :site_channels, only: %i(create update new show) do
    member do
      patch :update_unverified
      patch :check_for_https
      patch :verify
      get :download_verification_file
      get :verification_choose_method
      get :verification_dns_record
      get :verification_public_file
      get :verification_github
      get :verification_wordpress
    end
  end

  resources :static, only: [] do
    collection do
      get :index
    end
  end

  resources :faqs, only: [:index]

  root "static#index"
  get "no_js", controller: "static"
  get "sign-up", to: "static#index"
  get "log-in", to: "static#index"

  namespace :api, defaults: { format: :json } do
    # /api/v1/
    namespace :v1, defaults: { format: :json } do
      resources :publishers, defaults: { format: :json } do
        post "publisher_status_updates"
      end
      # /api/v1/stats/
      namespace :stats, defaults: { format: :json } do
        namespace :channels, defaults: { format: :json } do
          get :twitch_channels_by_view_count
          get :youtube_channels_by_view_count
        end
        resources :channels, defaults: { format: :json }, only: %i(show)
        resources :promo_campaigns, defaults: { format: :json }, only: %i(index show)
        resources :referral_codes, defaults: { format: :json }, only: %i(index show)
        namespace :publishers, defaults: { format: :json } do
          get :signups_per_day
          get :email_verified_signups_per_day
          get :channel_and_email_verified_signups_per_day
          get :channel_uphold_and_email_verified_signups_per_day
          get :channel_and_kyc_uphold_and_email_verified_signups_per_day
          get :javascript_enabled_usage
          get :totals
        end
      end
      # /api/v1/public/
      namespace :public, defaults: { format: :json } do
        get "channels", controller: "channels"
        namespace :channels, defaults: { format: :json } do
          get "totals"
        end
      end
    end
    # /api/v2/
    namespace :v2, defaults: { format: :json } do
      namespace :public, defaults: { format: :json } do
        get "channels", controller: "channels"
        namespace :channels, defaults: { format: :json } do
          get "totals"
        end
      end
    end
    # /api/v3/
    namespace :v3, defaults: { format: :json } do
      namespace :public, defaults: { format: :json } do
        get "channels", controller: "channels"
        namespace :channels, defaults: { format: :json } do
          get "totals"
        end
      end
    end
  end

  namespace :admin do
    resources :channels, only: [:index] do
      collection do
        get :duplicates
      end
    end

    resources :cases do
      patch :assign
      collection do
        get :overview
        resources :case_replies
      end
    end

    resources :case_notes

    resources :faq_categories, except: [:show]
    resources :faqs, except: [:show]
    resources :payout_reports do
      collection do
        post :notify
        post :upload_settlement_report
        post :toggle_payout_in_progress
      end
      member do
        get :download
        patch :refresh
      end
    end
    resources :publishers do
      collection do
        patch :approve_channel
        get :statement
        get :cancel_two_factor_authentication_removal
      end

      resources :payments
      patch :refresh_uphold

      resources :publisher_notes
      resources :publisher_status_updates, controller: "publishers/publisher_status_updates"
      resources :referrals, controller: "publishers/referrals"
      resources :reports
    end
    resources :channel_transfers
    resources :channel_approvals
    resources :security

    resources :organizations, except: [:destroy]
    resources :partners, except: [:destroy] do
      get :generate_manual_payout
      resources :invoices do
        post :upload
        get :finalize
        patch :update_status
      end
    end

    namespace :stats do
      resources :contributions, only: [:index]
      resources :referrals, only: [:index]
      resources :top_balances, only: [:index]
      resources :top_youtube_channels, only: [:index]
      resources :publisher_statistics, only: [:index]
    end
    resources :unattached_promo_registrations, only: %i(index create) do
      collection do
        get :report, defaults: { format: :csv }
        patch :update_statuses
        patch :assign_campaign
        put :assign_installer_type
      end
    end
    resources :promo_campaigns, only: %i(create)
    root to: "dashboard#index" # <--- Root route

    resources :uphold_status_reports, only: [:index, :show]
  end

  resources :errors, only: [], path: "/" do
    collection do
      get "400", action: :error_400
      get "401", action: :error_401
      get "403", action: :error_403
      get "404", action: :error_404
      get "422", action: :error_422
      get "500", action: :error_500
    end
  end

  require "sidekiq/web"
  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      # Protect against timing attacks: (https://codahale.com/a-lesson-in-timing-attacks/)
      # - Use & (do not use &&) so that it doesn't short circuit.
      # - Use `secure_compare` to stop length information leaking
      ActiveSupport::SecurityUtils.secure_compare(username, ENV["SIDEKIQ_USERNAME"]) &
        ActiveSupport::SecurityUtils.secure_compare(password, ENV["SIDEKIQ_PASSWORD"])
    end
  end
  mount Sidekiq::Web, at: "/magic"
  require "sidekiq/api"
  match "mailer-queue-status" => proc { [200, { "Content-Type" => "text/plain" }, [Sidekiq::Queue.new("mailer").size < 100 ? "OK" : "UHOH"]] }, via: :get
  match "default-queue-status" => proc { [200, { "Content-Type" => "text/plain" }, [Sidekiq::Queue.new("default").size < 5000 ? "OK" : "UHOH"]] }, via: :get
  match "scheduler-queue-status" => proc { [200, { "Content-Type" => "text/plain" }, [Sidekiq::Queue.new("scheduler").size < 5000 ? "OK" : "UHOH"]] }, via: :get
  match "transactional-queue-status" => proc { [200, { "Content-Type" => "text/plain" }, [Sidekiq::Queue.new("transactional").size < 5000 ? "OK" : "UHOH"]] }, via: :get
end

app/models/payout_report.rb
class PayoutReport < ApplicationRecord
  has_paper_trail
  self.per_page = 8

  LEGACY_PAYOUT_REPORT_TRANSITION_DATE = "2018-12-01 09:14:58 -0800".freeze

  attr_encrypted :contents, key: :encryption_key, marshal: true

  has_many :potential_payments

  validates_presence_of :expected_num_payments

  scope :final, -> {
    where(final: true)
  }

  def encryption_key
    # Truncating the key due to legacy OpenSSL truncating values to 32 bytes.
    # New implementations should use [Rails.application.secrets[:attr_encrypted_key]].pack("H*")
    Rails.application.secrets[:attr_encrypted_key].byteslice(0, 32)
  end

  def amount
    potential_payments.to_be_paid.sum { |potential_payment| potential_payment.amount.to_i }
  end

  def fees
    potential_payments.to_be_paid.sum { |potential_payment| potential_payment.fees.to_i }
  end

  def num_payments
    potential_payments.count
  end

  def num_payments_to_be_paid
    potential_payments.to_be_paid.count
  end

  def missing_addresses
    potential_payments.to_be_paid.unscope(where: :address).count - potential_payments.to_be_paid.count
  end

  def contribution_count
    potential_payments.pluck(:channel_id).compact.count
  end

  def referral_count
    potential_payments.count - contribution_count
  end

  def manage_expectations
    publishers = Publisher.joins(:uphold_connection).with_verified_channel
    channels = Channel.where(publisher_id: publishers.pluck(:id), verified: true)

    missing_channels = channels.pluck(:id) - potential_payments.pluck(:channel_id)
    missing_publishers = publishers.pluck(:id) - potential_payments.where(channel_id: nil).pluck(:publisher_id)
    { channels: missing_channels, publishers: missing_publishers }
  end

  # Updates the JSON summary of the report downloaded by admins
  def update_report_contents
    # Do not update json contents for legacy reports
    return if created_at <= LEGACY_PAYOUT_REPORT_TRANSITION_DATE
    if manual
      payout_report_hash = JsonBuilders::ManualPayoutReportJsonBuilder.new(payout_report: self).build
    else
      payout_report_hash = JsonBuilders::PayoutReportJsonBuilder.new(payout_report: self).build
    end
    self.contents = payout_report_hash.to_json
    save!
  end

  class << self
    def total_amount
      PayoutReport.sum { |payout_report| payout_report.amount }
    end

    def total_fees
      PayoutReport.sum { |payout_report| payout_report.fees }
    end

    def total_payments
      PayoutReport.sum { |payout_report| payout_report.num_payments }
    end

    def most_recent_final_report
      PayoutReport.all.where(final: true, manual: false).order("created_at").last
    end

    def expected_num_payments(publishers)
      channels = Channel.where(publisher_id: publishers.pluck(:id), verified: true)
      publishers.with_verified_channel.count + channels.count
    end
  end
end

app/controllers/admin/payout_reports_controller.rb
class Admin::PayoutReportsController < AdminController
  MANUAL = "manual"

  def index
    @payout_reports = PayoutReport.all.order(created_at: :desc).paginate(page: params[:page])
  end

  def show
    @payout_report = PayoutReport.find(params[:id])
    @previous_report = PayoutReport.where(
      manual: @payout_report.manual,
      final: @payout_report.final
    ).where("created_at < ?", @payout_report.created_at).order(created_at: :desc).take
  end

  def edit
    @payout_report = PayoutReport.find(params[:id])
  end

  def update
    @payout_report = PayoutReport.find(params[:id])
    if @payout_report.update(payout_params)
      redirect_to admin_payout_report_path(@payout_report), flash: { notice: "Saved"}
    else
      redirect_to admin_payout_report_path(@payout_report), flash: { alert: "Could not save"}
    end
  end

  def download
    @payout_report = PayoutReport.find(params[:id])
    contents = assign_authority(@payout_report.contents)
    send_data contents,
      filename: "payout-#{@payout_report.created_at.strftime("%FT%H-%M-%S")}",
      type: :json
  end

  def refresh
    UpdatePayoutReportContentsJob.perform_later(payout_report_ids: [params[:id]])
    redirect_to admin_payout_reports_path, flash: { notice: "Refreshing report JSON.  Please try downloading in a couple minutes." }
  end

  def create
    EnqueuePublishersForPayoutJob.perform_later(final: params[:final].present?, manual: params[:manual].present?)
    redirect_to admin_payout_reports_path, flash: { notice: "Your payout report is being generated, check back soon." }
  end

  def notify
    EnqueuePublishersForPayoutNotificationJob.perform_later
    redirect_to admin_payout_reports_path, flash: { notice: "Sending notifications to publishers with disconnected wallets." }
  end

  def upload_settlement_report
    content = File.read(params[:file].tempfile)
    json = JSON.parse(content)

    Eyeshade::Publishers.new.create_settlement(body: json)

    json.each do |entry|
      next unless entry["type"] == MANUAL && entry["owner"] && entry["amount"]

      partner_id = entry["owner"].sub(Publisher::OWNER_PREFIX, "")

      invoice = Invoice.where(
        partner_id: partner_id,
        finalized_amount: entry["amount"],
        status: Invoice::IN_PROGRESS
      ).order(:created_at).first

      next unless invoice.present?

      invoice.update(
        payment_date: Date.today,
        status: Invoice::PAID,
        paid_by: current_publisher
      )
    end

    redirect_to admin_payout_reports_path, flash: { notice: "Successfully uploaded settlement report" }
  rescue JSON::ParserError => e
    redirect_to admin_payout_reports_path, flash: { alert: "Could not parse JSON. #{e.message}" }
  rescue Faraday::ClientError => eyeshade_error
    redirect_to admin_payout_reports_path, flash: { alert: "Eyeshade responded with a 400 🤷‍️" }
  end

  def toggle_payout_in_progress
    payout_status = Rails.cache.fetch('payout_in_progress')
    Rails.cache.write('payout_in_progress', !payout_status)
    redirect_to admin_payout_reports_path, flash: { alert: "Set 'payout in progress' to #{!payout_status}" }
  end

  private

  def payout_params
    params.require(:payout_report).permit(:final)
  end

  def assign_authority(report_contents)
    report_contents = JSON.parse(report_contents)
    report_contents.each do |potential_payout|
      # Assign current admin as authority, unless it is a manual report.
      potential_payout["authority"] = current_publisher.email unless potential_payout["type"] == PotentialPayment::MANUAL
    end

    report_contents.to_json
  end
end

app/views/admin/payout_reports/edit.html.slim
.d-flex
  h2.m-0
    = "Edit Payout Report #{@payout_report.id[0..6]}"


= form_for [:admin, @payout_report], class: 'form' do |f|
  .form-check.form-group
    = f.check_box :final, class: 'form-check-input'
    = f.label :final, class: 'form-check-label'
  = submit_tag("Upate", class:' btn btn-primary')

app/views/admin/payout_reports/index.html.slim
.panel-heading
  h4 Payout Reports
  .d-flex
    = form_tag upload_settlement_report_admin_payout_reports_path, id: "settlementForm", multipart: :true
      label
        = file_field_tag :file, { class: 'd-none', id: "settlementFile",  accept: ".json,application/json" }
        .btn.btn-primary Upload Settlement Report

    = form_tag toggle_payout_in_progress_admin_payout_reports_path
      - toggle_text = Rails.cache.fetch('payout_in_progress') ? "Remove payout in progress" : "Set payout in progress"
      = submit_tag(toggle_text, class: "btn btn-primary")

javascript:
  document.getElementById('settlementFile').addEventListener("change", function() {
    document.getElementById('settlementForm').submit();
  })

hr

table.display.table.table-bordered.table-striped
  tr
    th Created
    th ID
    th Type
    th Manual
    th Expected - actual # of payments
    th # Payments to be paid
    th # Legit payments missing addresses
    th Amount
    th Refresh JSON
    th Download
  tbody
    - @payout_reports.each do |report|
      tr.gradeX
        td = report.created_at.strftime("%B %d, %Y, %H:%M")
        td = link_to report.id[0..6], admin_payout_report_path(report.id)
        td = report.final ? "Final" : "Temp"
        td = report.manual ? "Yes" : "No"
        td = "#{report.expected_num_payments} - #{report.num_payments}"
        td = report.num_payments_to_be_paid
        td = report.missing_addresses
        td = "#{'%.2f' % (report.amount.to_d / 1E18)} BAT"
        td = form_tag refresh_admin_payout_report_path(report.id), method: :patch do
             = submit_tag "refresh", class: "btn btn-info"
        / (Albert Wang) Check encrypted_contents_iv since encrypted_contents is a large fetch.
        td = report.encrypted_contents_iv.present? ? (link_to "download", download_admin_payout_report_path(report.id), class: "btn btn-primary") : "Please click 'refresh' on the left to create the contents"

hr

h3 Generate Payout Report
= form_tag admin_payout_reports_path do
    p Final - the report will be used in settlement.
    p Manual - the report will include only partners with finalized invoices. ** Note - A report can be both final and manual **
    = check_box_tag :final
    span = "   "
    = label_tag "Final"
    span = "   "
    = check_box_tag :manual
    span = "   "
    = label_tag "Manual"
    span = "   "
    = submit_tag("Generate", class: "btn btn-primary")
br

= form_tag notify_admin_payout_reports_path do
    = label_tag "Send notifications to publishers"
    span = "   "
    = submit_tag("Notify publishers", class: "btn btn-primary")
= will_paginate @payout_reports

app/views/admin/payout_reports/show.html.slim
.d-flex
  h2.m-0
    = "Payout Report #{@payout_report.id[0..6]}"
    br
    small.text-muted= @payout_report.created_at.strftime("%B %d, %Y, %H:%M")

  .ml-3
    = link_to "Edit", edit_admin_payout_report_path(@payout_report.id), class: 'btn btn-dark mr-1'
    = link_to "Refresh", refresh_admin_payout_report_path(@payout_report.id), method: :patch, class: 'btn btn-info'
    - if  @payout_report.encrypted_contents_iv.present?
      = link_to("Download", download_admin_payout_report_path(@payout_report.id), class: "btn btn-primary")
    - else
      span.ml-2.p-2.rounded.alert-info Click 'refresh' to create the contents

h6 Payout Details

.row
  .col-8
    table.table
      tr
        td
          .font-weight-bold Report type
          .small.w-75 This type determines the purpose of the report. There are 2 primary. Final and Temp. Manual or Automated

        td
          .d-flex
            - if @payout_report.final
              .badge.badge-primary data-tooltip="Indicates that the report is used as a source to pay out users during settlement." Final
            - else
              .badge.badge-light data-tooltip="Generated only for testing or informative purposes. Should not be used to pay users out" Temp

            - if @payout_report.manual
              .badge.badge-dark.ml-2 data-tooltip="Payments from manually entered invoices. Partners only." Manual
            - else
              .badge.badge-light.ml-2 data-tooltip="Standard payout report - all normal publishers are included." Automated
      tr
        td
          span.font-weight-bold Expected number of payouts
          .small.w-75
            span When the payout report is first generated we expect there to be the same number of payments as there are publishers and verified channels
        td= @payout_report.expected_num_payments

      tr
        td
          span.font-weight-bold Actual number of payouts
          .small.w-75 When the report has finished this represents the number of payments that we actually found available. This should almost always be equal to the expectated.
        td
          = @payout_report.num_payments
          - unless (@payout_report.expected_num_payments - @payout_report.num_payments).zero?
            .small
              span
                = @payout_report.expected_num_payments - @payout_report.num_payments
                = " payments missing - "
              = link_to "why?", why: true

      tr
        td
          span.font-weight-bold Payments to be made
          .small.w-75
            span Represents the number of payments that can be paid out. Meaning, user has completed kyc, and has a balance.

        td= @payout_report.num_payments_to_be_paid
      tr
        td.font-weight-bold Missing addresses
        td= @payout_report.missing_addresses
      tr
        td.font-weight-bold Amount
        td
          .d-flex.align-items-baseline
            = "#{number_with_delimiter((@payout_report.amount.to_d / 1E18).round(2))} BAT"
            - if @previous_report.present?
              small.ml-2 data-tooltip="percentage difference compared to previous report"
                = percentage_difference(@payout_report.amount.to_d, @previous_report.amount.to_d)

      - if @previous_report.present?
        tr
          td
            span.font-weight-bold Previous Payout Report
            .small.w-75
              =link_to(@previous_report.id[0..6], admin_payout_report_path(@previous_report))
              span= " run on #{@previous_report.created_at.strftime("%B %d, %Y, %H:%M")}"
          td
            = "#{number_with_delimiter((@previous_report.amount.to_d / 1E18).round(2))} BAT"

  .col-4
    #current-chart data-props="#{{contributionBalance: @payout_report.contribution_count, referralBalance: @payout_report.referral_count}.to_json}"
    table.table



- if @payout_report.missing_addresses > 0
  hr
  h6 Missing Addresses
  .alert.alert-warning.mb-2
    = fa_icon "warning"
    span There are missing addresses. This may cause some publishers to not get paid.
  table.table
    thead
      tr
        td Potential Payment ID
        td Publisher
        td Channel ID
        td Uphold ID
    tbody
    - @payout_report.potential_payments.to_be_paid.unscope(where: :address).where(address: '').each do |x|
      tr
        td= x.id
        td= link_to(x.publisher, admin_publisher_path(x.publisher_id))
        td= x.channel_id
        td= x.uphold_id



- if params[:why]
  h6 Payout Expectations vs. Reality
  p There are some possibilities why users might be on this report. For example, we assume that we're going to have a publisher amount. The publisher account status might be restricted, or locked state. This section is intended to assist in determining the cause.

  - expectations =  @payout_report.manage_expectations
  .font-weight-bold Channels not incuded
  table.table
    thead
      tr
        td Channel ID
    - if expectations[:channels].length.zero?
      tr
        td All channels were included.
    - expectations[:channels].each do |channel_id|
      tr
        td.small= channel_id

  .font-weight-bold Publishers not incuded
  table.table
    thead
      tr
        td Publisher ID
    - if expectations[:publishers].length.zero?
      tr
        td All publishers were included.
    - expectations[:publishers].each do |publisher_id|
      tr
        td.small= link_to(publisher_id, admin_publisher_path(publisher_id))


=javascript_pack_tag 'PayoutReports'